from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from repopilot.utils.file_utils import write_json, write_text


@dataclass(frozen=True)
class ReportPaths:
    report_json: Path
    readme_written: Path | None


class ReportGenerator:
    """
    Responsible for:
    - writing data/report.json
    - rendering README content (string)
    - optionally writing README.md into target project
    """

    def __init__(self, tool_name: str = "RepoPilot", version: str = "0.1.0") -> None:
        self.tool_name = tool_name
        self.version = version

    def build_report(self, payload: dict[str, Any]) -> dict[str, Any]:
        payload = dict(payload)
        payload.setdefault("meta", {})
        payload["meta"].update(
            {
                "tool": self.tool_name,
                "version": self.version,
                "generated_at": datetime.now().isoformat(timespec="seconds"),
            }
        )
        return payload

    def write_report_json(self, report_path: Path, report: dict[str, Any]) -> None:
        write_json(report_path, report)

    def render_readme(
        self,
        project_name: str,
        tree_text: str,
        analysis: dict[str, Any],
        summary: dict[str, Any],
        usage_examples: list[str],
    ) -> str:
        file_types: dict[str, int] = analysis.get("file_types", {})
        modules: list[str] = summary.get("modules", [])
        description: str = summary.get("description", "")

        lines: list[str] = []
        lines.append(f"# {project_name}")
        lines.append("")
        lines.append("Generated by **RepoPilot** (mock AI).")
        lines.append("")
        lines.append("## Overview")
        lines.append("")
        lines.append(description or "No summary available.")
        lines.append("")
        lines.append("## Key Modules (Mock AI)")
        lines.append("")
        if modules:
            for m in modules:
                lines.append(f"- {m}")
        else:
            lines.append("- (none)")
        lines.append("")
        lines.append("## File Type Statistics")
        lines.append("")
        if file_types:
            lines.append("| Extension | Count |")
            lines.append("|---|---:|")
            for ext, cnt in sorted(file_types.items(), key=lambda x: (-x[1], x[0]))[:20]:
                lines.append(f"| `{ext}` | {cnt} |")
        else:
            lines.append("(no files)")
        lines.append("")
        lines.append("## Project Tree (Preview)")
        lines.append("")
        lines.append("```text")
        lines.append(tree_text.strip())
        lines.append("```")
        lines.append("")
        lines.append("## How to Scan with RepoPilot")
        lines.append("")
        lines.append("```bash")
        for ex in usage_examples:
            lines.append(ex)
        lines.append("```")
        lines.append("")
        lines.append("## Output")
        lines.append("")
        lines.append("- `data/report.json` contains scan tree + file type stats + mock AI summary")
        lines.append("")
        lines.append("## License")
        lines.append("")
        lines.append("MIT (recommended).")
        lines.append("")
        return "\n".join(lines)

    def write_readme_to_target(self, target_dir: Path, content: str) -> Path:
        path = target_dir / "README.md"
        write_text(path, content)
        return path


